### ISSUE TITLE
File not found when loading up atom

### ISSUE THREAD

**Issue by SaraVieira** [alanzanattadev/atom-molecule-dev-environment#184]
Hey guys, 

Really excited about this ! 

Problem is whenever I try to boot uo atom I get this:

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [molecule-dev-environment](https://github.com/alanzanattadev/atom-molecule-dev-environment) package 0.2.0

### Stack Trace

Failed to load the molecule-dev-environment package

```
At Cannot find module '../build/Release/pty.node'

Error: Cannot find module '../build/Release/pty.node'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/saravieira/atom-molecule-dev-environment/node_modules/node-pty/lib/unixTerminal.js:17:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/saravieira/atom-molecule-dev-environment/node_modules/node-pty/lib/index.js:9:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/saravieira/atom-molecule-dev-environment/lib/ExecutionControlEpic/TaskExecutionFeature/Model/Strategies/ShellStrategy.js:6:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
     -3:37 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.use-animations.theme-atom-material-syntax.theme-atom-material-ui)
     -2:55.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

Any ideas ?

Thank you

**Comment by alanzanattadev** [comment]
Hi Sara,

I see you're on the 0.2.0 which is broken for a weird reason for now, checkout to v0.1.1 for now and we'll fix this soon ! :)

**Comment by SaraVieira** [comment]
Hello @alanzanattadev 

It's working now ! Awesome !

Thank you 👍
