### ISSUE TITLE
Error when opening versioning panel

### ISSUE THREAD

**Issue by Kendos-Kenlen** [alanzanattadev/atom-molecule-dev-environment#197]
1. Open Molecule
2. Open versioning panel on a project using git

**Atom**: 1.16.0 x64
**Electron**: 1.4.16
**OS**: linux 4.10.13-1-ARCH
**Thrown From**: [molecule-dev-environment](https://github.com/alanzanattadev/atom-molecule-dev-environment) package 0.2.0

### Stack Trace

Uncaught TypeError: value.get is not a function

```
At /work/Molecule/atom-molecule-dev-environment/lib/VersionningEpic/StashFeature/Model/stashList.js:43

TypeError: value.get is not a function
    at /work/Molecule/atom-molecule-dev-environment/lib/VersionningEpic/StashFeature/Model/stashList.js:43:38
    at /work/Molecule/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:4420:31
    at List.__iterate (/work/Molecule/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:2208:13)
    at List.reduce (/work/Molecule/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:4415:12)
    at /work/Molecule/atom-molecule-dev-environment/lib/VersionningEpic/StashFeature/Model/stashList.js:35:10
    at Array.map (native)
    at getStashesFromStashListOutput (/work/Molecule/atom-molecule-dev-environment/lib/VersionningEpic/StashFeature/Model/stashList.js:14:6)
    at /work/Molecule/atom-molecule-dev-environment/lib/VersionningEpic/StashFeature/Actions/StashList.js:21:33
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Non-Core Packages

```
molecule-dev-environment 0.2.0 
```

**Comment by lorenzoalfieri** [comment]
Disabling versionning panel #205 .
Since atom is doing a git integration in 1.18, we  don't need it anymore.
