### ISSUE TITLE
Exception thrown when opening terminal view

### ISSUE THREAD

**Issue by GauthierPLM** [alanzanattadev/atom-molecule-dev-environment#231]
1. Start a diagnostic
2. Open the terminal view => the exception is thrown

Happens on Linux and Mac OS

This looks to happen when resizing the terminal.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [molecule-dev-environment](https://github.com/alanzanattadev/atom-molecule-dev-environment) package 0.4.0

### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/node-pty/lib/unixTerminal.js:161

Error: ioctl(2) failed.
    at Error (native)
    at UnixTerminal.resize (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/node-pty/lib/unixTerminal.js:161:13)
    at Terminal.<anonymous> (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/lib/ExecutionControlEpic/TaskExecutionFeature/Actions/RunTask.js:160:55)
    at Terminal.EventEmitter.emit (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/xterm/lib/EventEmitter.js:46:20)
    at Terminal.resize (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/xterm/lib/xterm.js:1324:10)
    at Object.exports.fit (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/xterm/lib/addons/fit/fit.js:73:12)
    at Terminal.Xterm.fit (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/xterm/lib/addons/fit/fit.js:82:20)
    at Term.initTerm (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/lib/ExecutionControlEpic/ActionSystemFeature/Presenters/Term.js:24:30)
    at Term.componentDidMount (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/lib/ExecutionControlEpic/ActionSystemFeature/Presenters/Term.js:30:12)
    at CallbackQueue.notifyAll (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/CallbackQueue.js:76:22)
    at ReactReconcileTransaction.close (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
    at ReactReconcileTransaction.closeAll (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/Transaction.js:206:25)
    at ReactReconcileTransaction.perform (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/Transaction.js:153:16)
    at ReactUpdatesFlushTransaction.perform (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/Transaction.js:140:20)
    at ReactUpdatesFlushTransaction.perform (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/ReactUpdates.js:89:32)
    at Object.flushBatchedUpdates (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/Transaction.js:206:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/Transaction.js:153:16)
    at Object.batchedUpdates (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Users/gauthierpogam--lemontagner/WebstormProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/ReactEventListener.js:147:20)
```

### Commands

```
     -3:47.1.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-firewatch-hot-syntax.theme-one-dark-ui)
     -0:55.3.0 application:add-project-folder (input.hidden-input)
```

### Non-Core Packages

```
firewatch-hot-syntax 1.3.0 
molecule-dev-environment 0.4.0 
```

**Comment by Newtchuck** [comment]
Transfered to Trello (en attente de release)
