### ISSUE TITLE
Number of diagnostics doesn't disappear when deleting plan

### ISSUE THREAD

**Issue by GauthierPLM** [alanzanattadev/atom-molecule-dev-environment#242]
The number of diagnostic displayed next to the tool icon doesn't disappear when the plan is deleted. It create an exception if clicked on.

[Enter steps to reproduce:]

1. Create a plan, run it and delete it;
2. Click on the number of diagnostics, the exception is thrown.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [molecule-dev-environment](https://github.com/alanzanattadev/atom-molecule-dev-environment) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/ReactErrorUtils.js:51

TypeError: Cannot read property 'remove' of undefined
    at areSamePlans (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/lib/ExecutionControlEpic/PlanConfigurationFeature/Model/PlanManipulators.js:10:18)
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/lib/ExecutionControlEpic/TaskExecutionFeature/Selectors/Tasks.js:102:21
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:3086:23
    at List.__iterate (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.filterSequence.__iterateUncached (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:3085:16)
    at seqIterate (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.forEach (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:4383:19)
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:2071:14
    at List.Map.withMutations (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:1355:7)
    at new List (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:2069:20)
    at reify (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:3572:37)
    at List.filter (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/immutable/dist/immutable.js:4730:14)
    at selectTasksOfPlan (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/lib/ExecutionControlEpic/TaskExecutionFeature/Selectors/Tasks.js:102:6)
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/lib/ExecutionControlEpic/DiagnosticsFeature/Containers/ToolDiagnosticsTraveller.js:123:10
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/withProps.js:19:62
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/mapProps.js:19:22
    at createEagerElementUtil (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/utils/createEagerElementUtil.js:18:12)
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/createEagerFactory.js:18:49
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/mapProps.js:19:14
    at createEagerElementUtil (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/utils/createEagerElementUtil.js:18:12)
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/createEagerFactory.js:18:49
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/mapProps.js:19:14
    at createEagerElementUtil (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/utils/createEagerElementUtil.js:18:12)
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/createEagerFactory.js:18:49
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/mapProps.js:19:14
    at createEagerElementUtil (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/utils/createEagerElementUtil.js:18:12)
    at /Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/createEagerFactory.js:18:49
    at render (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/recompose/lifecycle.js:30:16)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/gauthier/IdeaProjects/atom-molecule-dev-environment/node_modules/react-dom/lib/ReactCompositeComponent.js:799:30)
```

### Commands

```
```

### Non-Core Packages

```
molecule-dev-environment 0.4.0 
```

**Comment by Newtchuck** [comment]
Fixed ?
