### ISSUE TITLE
Installing with wrong nodejs version

### ISSUE THREAD

**Issue by charlesinwald** [alanzanattadev/atom-molecule-dev-environment#256]
1. ... Install latest nodejs
2. ... Install molecule and start atom

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [molecule-dev-environment](https://github.com/alanzanattadev/atom-molecule-dev-environment) package 0.4.0

### Stack Trace

Failed to load the molecule-dev-environment package

```
At The module '/home/charles/atom-molecule-dev-environment/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

Error: The module '/home/charles/atom-molecule-dev-environment/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/charles/atom-molecule-dev-environment/node_modules/node-pty/lib/unixTerminal.js:17:11)
    at Object.<anonymous> (/home/charles/atom-molecule-dev-environment/node_modules/node-pty/lib/unixTerminal.js:190:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/charles/atom-molecule-dev-environment/node_modules/node-pty/lib/index.js:9:16)
    at Object.<anonymous> (/home/charles/atom-molecule-dev-environment/node_modules/node-pty/lib/index.js:31:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/charles/atom-molecule-dev-environment/lib/ExecutionControlEpic/TaskExecutionFeature/Model/Strategies/ShellStrategy.js:6:16)
    at Object.<anonymous> (/home/charles/atom-molecule-dev-environment/lib/ExecutionControlEpic/TaskExecutionFeature/Model/Strategies/ShellStrategy.js:41:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
```

### Commands

```
```

### Non-Core Packages

```
molecule-dev-environment 0.4.0 
```

**Comment by alanzanattadev** [comment]
Hi,

please try to rerun the script ./fix-node-pty. Maybe Atom has been updated and it needs to recompile node-pty. If you still have the issue, let me know

**Comment by charlesinwald** [comment]
How do I run that javascript?

**Comment by alanzanattadev** [comment]
npm run fix-node-pty :)

**Comment by charlesinwald** [comment]
Atom starts without an error, whats a good way to test molecule functionality?  Thank you so much for your help!

**Comment by alanzanattadev** [comment]
Molecule is still in pre-alpha, so not everything is working correctly. The best experience we provide is with Jest, try running it from Molecule.

To do so:
  - click on the name of the tool
  - create a plan (which is configuration for the runner)
  - click on the plan button to run it
  - then click on the tool icon
  - you have on the left the terminal and the diagnostics
  - on the terminal you can use jest as you're used to use it, diagnostics are relevant informations
  - try to make jest output results and see what happens in molecule :)

**Comment by alanzanattadev** [comment]
Also, provide us feedback if you want a feature or something to be fixed :) We're working on integration of real time diagnostics for tools like ESLint and FlowType. It's coming soon.

**Comment by charlesinwald** [comment]
I'm actually getting the error I had before, I tried rerunning npm run fix-node-pty.

Also I just noticed earlier I had the following during the "yarn" step:

warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.

**Comment by alanzanattadev** [comment]
It's not supposed to create a problem, it's an optional dependency. try to remove node_modules, and run yarn again

**Comment by charlesinwald** [comment]
Same issue I'm afraid

**Comment by alanzanattadev** [comment]
Does atom ask you for rebuilding the package in the status-bar (on the bottom) ?

**Comment by charlesinwald** [comment]
Nope, just in the stacktrace it says "Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`)".

**Comment by alanzanattadev** [comment]
Maybe you can also try to git checkout master, and then to remove node_modules and reinstall with yarn again, to see if even the last version is concerned

**Comment by charlesinwald** [comment]
Node_modules reappeared.

**Comment by alanzanattadev** [comment]
Does it work ?

**Comment by charlesinwald** [comment]
Unfortunately no.

**Comment by alanzanattadev** [comment]
Ok so you're facing a real issue, I will investigate that and get back to you soon, sorry for this

**Comment by charlesinwald** [comment]
Also if I run npm list I get:

npm ERR! invalid: react-forms-state@2.6.1 /home/charles/atom-molecule-dev-environment/node_modules/react-forms-state
npm ERR! extraneous: ajv@5.2.2 /home/charles/atom-molecule-dev-environment/node_modules/ajv-keywords/node_modules/ajv

**Comment by alanzanattadev** [comment]
Use yarn, it's more accurate for dependency management on Molecule ;)

**Comment by GauthierPLM** [comment]
Hello,

We use a pre-compiled version of node-pty for a while now. This should have solved the issue.
Please let us know if you still have this problem.
