### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not ...

### ISSUE THREAD

**Issue by giardb** [alanzanattadev/atom-molecule-dev-environment#427]
[Enter steps to reproduce:]

1. Npm start of big project, when the project finish to build.

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [molecule](https://github.com/alanzanattadev/atom-molecule-dev-environment) package 1.0.4

### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

```
At /Users/boris/.atom/packages/molecule/node_modules/xterm/lib/Renderer.js:67

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Renderer._refresh (/packages/molecule/node_modules/xterm/lib/Renderer.js:67:40)
    at Renderer._refreshLoop (/packages/molecule/node_modules/xterm/lib/Renderer.js:60:14)
```

### Commands

```
     -3:57.5.0 settings-view:open (input.hidden-input)
     -3:52.7.0 core:confirm (input.hidden-input)
  2x -2:51.1.0 datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
autocomplete-modules 2.2.0 
busy-signal 1.4.3 
file-icons 2.1.24 
ide-flowtype 0.23.1 
ide-json 0.2.1 
ide-typescript 0.7.6 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
molecule 1.0.4 
prettier-atom 0.55.2 
project-manager 3.3.6 
```

**Comment by GauthierPLM** [comment]
Should be fixed in last release (v1.1).
