### ISSUE TITLE
Uncaught Error: Could not release an element not yet acquired

### ISSUE THREAD

**Issue by MrElan** [alanzanattadev/atom-molecule-dev-environment#443]
[Enter steps to reproduce:]

1. Pin shell plan
2. Click on blue floating action button

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Debian GNU/Linux
**Thrown From**: [molecule](https://github.com/alanzanattadev/atom-molecule-dev-environment) package 1.0.4

### Stack Trace

Uncaught Error: Could not release an element not yet acquired

```
At /home/elan/.atom/packages/molecule/node_modules/xterm/lib/utils/DomElementObjectPool.js:23

Error: Could not release an element not yet acquired
    at DomElementObjectPool.release (/packages/molecule/node_modules/xterm/lib/utils/DomElementObjectPool.js:23:19)
    at Renderer._refresh (/packages/molecule/node_modules/xterm/lib/Renderer.js:95:45)
    at Renderer._refreshLoop (/packages/molecule/node_modules/xterm/lib/Renderer.js:60:14)
```

### Commands

```
  2x -2:34 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-jinja2 0.6.0 
auto-indent 0.5.0 
autocomplete-ansible 0.1.24 
autocomplete-python 1.11.0 
language-ansible 0.2.2 
molecule 1.0.4 
python-tools 0.6.9 
```

**Comment by GauthierPLM** [comment]
Should be fixed in last release (v1.1).

Please let us know if you still encounter this issue.
